home:
  path: /
  controller: App\Controller\DefaultController::home

login:
  path: /login
  controller: App\Controller\DefaultController::login

register:
  path: /register
  controller: App\Controller\DefaultController::register

logout:
  path: /logout
  controller: App\Controller\DefaultController::logout

chatbox:
  path: /chatbox
  controller: App\Controller\DefaultController::chatbox