home:
  path: /
  controller: App\Controller\DefaultController::home

login:
  path: /login
  controller: App\Controller\DefaultController::login

register:
  path: /register
  controller: App\Controller\DefaultController::register